import { Project } from './types';

export const projectsData: Project[] = [
  {
    id: 1,
    title: "Subodh Notifier",
    description: "A notifier system for Subodh College that delivers announcements and alerts via API and Docker container.",
    image: "https://loremflickr.com/600/400/college",
    tags: ["Node.js", "Express", "Docker"],
    demoLink: "https://github.com/mrsandyy/subodh-notifier",
    repoLink: "https://github.com/mrsandyy/subodh-notifier",
    featured: true,
    caseStudy: {
      headline: "Simplified real-time announcement system for students and faculty.",
      challenges: "Maintaining a lightweight and portable system with offline capabilities.",
      backendHighlights: [
        "Stateless API using Express",
        "Deployed via Docker for portability",
        "Basic authentication for updates",
      ],
      mainStack: ["Node.js", "Express", "Docker"],
    },
  },
  {
    id: 2,
    title: "Rapture Tours Website",
    description: "A full-featured travel agency website with destination highlights, tour packages, contact form, and admin content management.",
    image: "https://loremflickr.com/600/400/travel",
    tags: ["Next.js", "TypeScript", "Travel", "CMS"],
    demoLink: "https://rapturetours.com",
    repoLink: "https://github.com/mrsandyy/rapture-tours",
    featured: true,
    caseStudy: {
      headline: "A sleek travel agency platform with tour showcases and booking inquiries.",
      challenges: "Designing an intuitive layout for tour listings and managing content efficiently.",
      backendHighlights: [
        "Dynamic tour and destination pages",
        "Integrated contact and inquiry system",
        "Admin content panel for easy updates",
      ],
      mainStack: ["Next.js", "TypeScript", "Tailwind CSS", "Node.js"],
    },
  },
  {
    id: 3,
    title: "Web Automation Suite",
    description: "A series of web automation scripts and bots for platforms like Instagram, Snapchat, and Spotify for content posting, user activity simulation, and more.",
    image: "https://loremflickr.com/600/400/technology",
    tags: ["Python", "Automation", "Selenium", "Botting"],
    demoLink: "https://github.com/mrsandyy/web-automation-suite",
    repoLink: "https://github.com/mrsandyy/web-automation-suite",
    featured: false,
    caseStudy: {
      headline: "Time-saving scripts to automate routine actions on major social platforms.",
      challenges: "Bypassing detection mechanisms, ensuring consistent browser behavior, and handling dynamic content.",
      backendHighlights: [
        "Browser automation with Selenium",
        "Task scheduling with cron jobs",
        "Multi-platform login/session handling",
      ],
      mainStack: ["Python", "Selenium", "Playwright"],
    },
  },
  {
    id: 4,
    title: "CareVision - Elder Assistance AI",
    description: "An AI-powered camera vision system that helps the elderly remember their belongings and daily schedule through smart alerts and tracking.",
    image: "https://loremflickr.com/600/400/elderly,technology",
    tags: ["AI", "Computer Vision", "IoT", "Healthcare"],
    demoLink: "#",
    repoLink: "https://github.com/mrsandyy/carevision",
    featured: true,
    caseStudy: {
      headline: "Helping elders with memory assistance using AI vision technology.",
      challenges: "Implementing object detection reliably and minimizing false positives in a home setting.",
      backendHighlights: [
        "YOLO-based object tracking",
        "Schedule reminders via speech or screen",
        "Alert system for misplaced items",
      ],
      mainStack: ["Python", "OpenCV", "TensorFlow", "Raspberry Pi"],
    },
  },
  {
    id: 5,
    title: "StudyBits – Subodh Notes Website",
    description: "Dynamic site that serves BCA course notes from Markdown files with folder-based navigation, supporting PDFs.",
    image: "https://loremflickr.com/600/400/education",
    tags: ["TypeScript", "Next.js", "Education", "Markdown"],
    demoLink: "https://studybits.inorc.com",
    repoLink: "https://github.com/mrsandyy/subodh-notes",
    featured: true,
    caseStudy: {
      headline: "Organized educational content for college students in a clean, interactive UI.",
      challenges: "Rendering nested markdown files and PDFs with intuitive navigation.",
      backendHighlights: [
        "Recursive folder structure support",
        "Custom PDF navigation",
        "Minimalist and responsive design",
      ],
      mainStack: ["Next.js", "TypeScript", "Tailwind CSS"],
    },
  },
  {
    id: 6,
    title: "InspireBot - Discord Quote Bot",
    description: "A motivational bot for Discord that sends random inspirational quotes in channels or via command.",
    image: "https://loremflickr.com/600/400/discord",
    tags: ["Discord.js", "Node.js", "Bot"],
    demoLink: "https://discord.com/oauth2/authorize?client_id=1234567890",
    repoLink: "https://github.com/mrsandyy/inspirebot",
    featured: false,
    caseStudy: {
      headline: "Keeping Discord servers motivated with random quotes.",
      challenges: "Creating a light and spam-free experience with customizable intervals.",
      backendHighlights: [
        "Quote API integration",
        "Command-based and auto-post features",
        "Permission and channel filters",
      ],
      mainStack: ["Node.js", "Discord.js"],
    },
  },
  {
    id: 7,
    title: "CampusConnect – College Website",
    description: "A comprehensive website for a college, featuring course listings, faculty profiles, event calendars, and an online admission portal.",
    image: "https://loremflickr.com/600/400/campus",
    tags: ["Next.js", "TypeScript", "Education", "CMS"],
    demoLink: "https://campusconnect.edu",
    repoLink: "https://github.com/mrsandyy/campusconnect",
    featured: true,
    caseStudy: {
      headline: "Digital transformation of college outreach and administration.",
      challenges: "Integrating dynamic content management with a user-friendly interface for students and faculty.",
      backendHighlights: [
        "Custom CMS for course and faculty management",
        "Event calendar with RSVP functionality",
        "Secure online admission forms with document uploads",
      ],
      mainStack: ["Next.js", "TypeScript", "Tailwind CSS", "Node.js"],
    },
  },
  {
    id: 8,
    title: "FitLife – Gym Website",
    description: "A modern website for a gym, showcasing workout programs, trainer profiles, class schedules, and membership sign-ups.",
    image: "https://loremflickr.com/600/400/gym",
    tags: ["React", "Fitness", "Booking", "Responsive Design"],
    demoLink: "https://fitlifegym.com",
    repoLink: "https://github.com/mrsandyy/fitlife",
    featured: false,
    caseStudy: {
      headline: "Enhancing gym member engagement through a dynamic web platform.",
      challenges: "Creating an intuitive interface for class bookings and trainer interactions.",
      backendHighlights: [
        "Interactive class schedule with booking system",
        "Trainer profiles with specialization filters",
        "Membership management with payment integration",
      ],
      mainStack: ["React", "Node.js", "Express", "MongoDB"],
    },
  },
  {
    id: 9,
    title: "EduKids – School Website",
    description: "A vibrant website for a primary school, featuring class activities, parent-teacher communication portals, and academic resources.",
    image: "https://loremflickr.com/600/400/school",
    tags: ["Vue.js", "Education", "Communication", "Responsive Design"],
    demoLink: "https://edukidschool.org",
    repoLink: "https://github.com/mrsandyy/edukids",
    featured: false,
    caseStudy: {
      headline: "Bridging the gap between school and home with an interactive platform.",
      challenges: "Facilitating seamless communication between teachers and parents.",
      backendHighlights: [
        "Secure parent-teacher messaging system",
        "Gallery of class activities and events",
        "Downloadable academic resources and homework assignments",
      ],
      mainStack: ["Vue.js", "Firebase", "Tailwind CSS"],
    },
  },
  {
    id: 10,
    title: "MyPortfolio – Personal Website",
    description: "A personal portfolio website to showcase projects, blogs, and contact information, reflecting a professional online presence.",
    image: "https://loremflickr.com/600/400/portfolio",
    tags: ["Gatsby", "Portfolio", "Blog", "Responsive Design"],
    demoLink: "https://myportfolio.dev",
    repoLink: "https://github.com/mrsandyy/myportfolio",
    featured: true,
    caseStudy: {
      headline: "Establishing a personal brand through a sleek and informative website.",
      challenges: "Designing a platform that effectively showcases skills and projects.",
      backendHighlights: [
        "Markdown-based blog system",
        "Project showcase with detailed case studies",
        "Contact form with email integration",
      ],
      mainStack: ["Gatsby", "GraphQL", "Styled Components"],
    },
  },
  {
    id: 11,
    title: "Vision & Automation Mini Projects",
    description: "A set of small tools using computer vision and automation – object counters, screen bots, face detection scripts, and more.",
    image: "https://loremflickr.com/600/400/technology",
    tags: ["OpenCV", "Python", "Automation", "Computer Vision"],
    demoLink: "https://github.com/mrsandyy/vision-automation-scripts",
    repoLink: "https://github.com/mrsandyy/vision-automation-scripts",
    featured: false,
    caseStudy: {
      headline: "Simple tools built to demonstrate computer vision and system automation.",
      challenges: "Balancing simplicity with robustness in automation routines.",
            backendHighlights: [
        "Face detection and recognition",
        "Mouse/keyboard automation using image templates",
        "Object counting and tracking via OpenCV",
      ],
      mainStack: ["Python", "OpenCV", "PyAutoGUI", "Tesseract OCR"],
    },
  },
  {
    id: 12,
    title: "DotNet Mini Projects",
    description: "A collection of small desktop applications made using C# and .NET for academic and utility purposes.",
    image: "https://loremflickr.com/600/400/windows",
    tags: [".NET", "C#", "WinForms", "Desktop App"],
    demoLink: "https://github.com/mrsandyy/dotnet-mini-projects",
    repoLink: "https://github.com/mrsandyy/dotnet-mini-projects",
    featured: false,
    caseStudy: {
      headline: "Lightweight desktop apps solving everyday problems and academic tasks.",
      challenges: "Creating easy-to-use UIs with event-driven logic.",
      backendHighlights: [
        "WinForms-based UI",
        "File I/O operations",
        "Simple local DB storage (SQLite)",
      ],
      mainStack: ["C#", ".NET Framework", "WinForms"],
    },
  },
  {
    id: 13,
    title: "Inorc – Social Media Agency Website",
    description: "The website for your registered digital agency, featuring services, projects, blogs, and an AI-powered pricing assistant.",
    image: "https://loremflickr.com/600/400/business,agency",
    tags: ["Next.js", "Tailwind CSS", "Node.js", "AI", "SEO"],
    demoLink: "https://inorc.com",
    repoLink: "https://github.com/mrsandyy/inorc-agency",
    featured: true,
    caseStudy: {
      headline: "Official digital presence of Inorc – your creative and software agency.",
      challenges: "Designing a fast, SEO-optimized platform with multiple content sections and chatbot integration.",
      backendHighlights: [
        "AI chatbot for cost estimation",
        "Dynamic blog and showcase systems",
        "Admin panel for project and blog management",
      ],
      mainStack: ["Next.js", "TypeScript", "Tailwind", "Node.js", "PostgreSQL", "Redis"],
    },
  },
  {
    id: 14,
    title: "SaaS POS System (Petpooja Inspired)",
    description: "A POS system inspired by Petpooja for restaurants, supporting offline-first, multi-platform, order management, and analytics.",
    image: "https://loremflickr.com/600/400/restaurant",
    tags: ["SaaS", "POS", "Electron", "PWA", "Offline Support"],
    demoLink: "#",
    repoLink: "https://github.com/mrsandyy/pos-system",
    featured: true,
    caseStudy: {
      headline: "A complete POS system tailored for restaurant use, designed for offline and multi-device support.",
      challenges: "Ensuring offline functionality and real-time sync when online, across devices.",
      backendHighlights: [
        "Local-first database with sync logic",
        "Multi-user/table order tracking",
        "Sales analytics and reports",
      ],
      mainStack: ["Node.js", "Express", "IndexedDB", "Electron", "React", "SQLite"],
    },
  },
];
